#logging.level.org.springframework.web.servlet: DEBUG
#spring.profiles.active: prod
app.name: in28Minutes
welcome.message: Welcome message from property file! Welcome to ${app.name}

spring:
  datasource:
#    url: jdbc:sqlserver://10.54.4.21;databaseName=adp;encrypt=true;trustServerCertificate=true
#    username: sa
#    password: Supcon@1304
    url: jdbc:oracle:thin:@192.168.95.106:1521:orcl
    username: adp
    password: 1
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
#    username: root
#    password:

basic:
  value: true
  message: Dynamic Message
  number: 100