#logging.level.org.springframework.web.servlet: DEBUG
#spring.profiles.active: prod
app.name: in28Minutes
welcome.message: Welcome message from property file! Welcome to ${app.name}

spring:
  datasource:
    url: jdbc:sqlserver://10.54.4.21;databaseName=adp;encrypt=true;trustServerCertificate=true
    username: sa
    password: Supcon@1304

basic:
  value: true
  message: Dynamic Message
  number: 100